name: Firmware build

on: 
    push:
        branches: [main]
    
    pull_request:
        branches: [main]
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            
            - name: Build STM32 firmware
              uses: xanderhendriks/action-build-stm32cubeide@v10.0
              with:
                project-path: 'STM32'
                project-target: 'CAN_Data_Acquisition/Debug'
                stm32cubeide-version: '16.0'